for i in range(5):  #range(stop)
    print("sanjib",i)
print("\n")
for i in range(1,5):  #range(start,stop)
    print("sanjib",i)
print("\n")
for i in range(1,10,2): #range(start,stop,step)
    print("sanjib",i)
